version: '3.8'
services:
    expense-tracker-frontend:
      image: parthkarad/expense-tracker-frontend-v2:latest
      hostname: saffron-expensetracker.com
      ports:
        - "3000:80"
      networks:
        - expense
      depends_on:
        - expense-tracker-backend
    expense-tracker-backend:
      image: parthkarad/expense-tracker-backend-v2:latest
      hostname: expense-java-app
      ports:
        - "8081:8080"
      environment:
        - SERVER_PORT=8080
        - MONGODB_URL=mongodb://mongo:27017/expense-tracker
      volumes:
        - ./:/app
      networks:
        - expense
      depends_on:
        - mongo

    mongo:
      image: mongo
      hostname: mydb
      ports:
        - 27017:27017
      volumes:
        - /home/om17/mongodb:/data/db
        - /home/om17/mongodb_config:/data/configdb
      networks:
        - expense

networks:
  expense:
    name: expense
